version: '3.1'

services:
  web:
    restart: always
    image: go-mysql-crud
    ports:
      - 8005:8005
    links:
      - mysql
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=localhost"
      - "DB_NAME=x-charts"
      - "DB_PASS="
  
  mysql:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - /Users/songwing/Downloads/workspace/volumes/mydb:/var/lib/mysql
    
