version: '3.1'

services:
  web:
    restart: always
    image: go-mysql-crud
    ports:
      - 8005:8005
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "DB_NAME=x-charts"
      - "DB_PASS="
    networks:
      - mynet
    container_name: "x-charts-api"
  
  mysql:
    image: bitnami/mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - /Users/songwing/Downloads/workspace/volumes/mydb:/bitnami/mariadb/data
    networks:
      - mynet
    container_name: "mysql"
    hostname: "mariadb"

networks:
    mynet:
